baseURL: "https://corb.co"
languageCode: "en-us"
title: "corb.co"
theme: "PaperMod"

pagination:
  pagerSize: 5

menu:
  main:
    - name: About
      url: about
      weight: 10
    - name: Posts
      url: posts
      weight: 20

enableRobotsTXT: false
# buildDrafts: false
# buildFuture: false
# buildExpired: false

# googleAnalytics: UA-123-45

params:
  # env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: corb.co
  description: "Personal and projects site for Corban Mailloux"
  author: Corban Mailloux

  # images: ["<link or path of image for opengraph, twitter-cards>"]

  ShowReadingTime: true
  ShowShareButtons: false
  comments: false
  disableScrollToTop: true

  # Disable light/dark switching for now.
  defaultTheme: light
  disableThemeToggle: true

  disableSpecial1stPost: false

  assets:
    # disableHLJS: true # to disable highlightjs
    # disableFingerprinting: true
    favicon: "/icons/favicon.ico"
    favicon16x16: "/icons/favicon-16x16.png"
    favicon32x32: "/icons/favicon-32x32.png"
    apple_touch_icon: "/icons/apple-touch-icon.png"
    safari_pinned_tab: "/icons/safari-pinned-tab.svg"

  label:
    # text: "corb.co"
    icon: /icons/logo.min.svg
    iconHeight: 38

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: üëãüèº Hey! I'm Corban.
    subtitle: |
      üçº Dad

      üíª Engineer

      [üí° Home Automator](https://github.com/corbanmailloux/home-assistant-configuration)

      [üé∑ Musician](https://wellsuitedband.com)

      üéÆ FPV Drone Pilot

      [üêà Amateur Cat Trainer](https://www.instagram.com/theladies_sashaandmaya/)

      ‚úÖ Hobby Collector
    imageUrl: "/images/corban-mailloux.jpg"
    imageWidth: 300
    imageHeight: 300
    imageTitle: Headshot of Corban Mailloux
    buttons:
      - name: Posts
        url: posts

  # home-info mode
  homeInfoParams:
    Title: "Welcome!"
    Content: blank

  socialIcons:
    - name: email
      url: mailto:web@corb.co
    - name: github
      url: "https://github.com/corbanmailloux"
    - name: instagram
      url: "https://www.instagram.com/corbanmailloux/"
    - name: linkedin
      url: "https://www.linkedin.com/in/corbanmailloux"

  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    responsiveImages: false
    hiddenInList: true # hide on list pages and home
    # hiddenInSingle: false # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

markup:
  goldmark:
    renderer:
      unsafe: true
